#!/usr/bin/env bash

# Read in a list of sha1 ids with some other information and append the output
# of "file" called on each blob to each line
#
idexpr='^[[:xdigit:]]{40}'
while read -r id rest
do
    fstr=
    if [[ $id =~ $idexpr ]]
    then
        fstr=$(git cat-file blob "$id" | file -)
        fstr=${fstr#/dev/stdin: }
    fi
    printf '%s\n' "$id $rest${fstr+ ${fstr}}"
done

#   Copyright (C) 2015,2016 Bloomberg Finance L.P.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
