#!/bin/sh

# SC2016: Expressions don't expand in single quotes, use double quotes for that.
# shellcheck disable=SC2016
if test $# -eq 2
then
    script='{ if ($(NF - 1) >= '$1' && $(NF - 1) < '$2') { print }}'
else
    script='{ if ($(NF - 1) >= '$1') { print }}'
fi

git cat-file --batch-all-objects --batch-check='%(objectname) %(objectsize) %(objecttype)' --buffer |
    awk '{ if ($3 == "blob") { print $1, $2 }}' |
    "$(dirname "$0")"/scripts/fillout-delta |
    awk "$script"

#   Copyright (C) 2015,2016 Bloomberg Finance L.P.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
