#!/bin/sh

if ! test -f "$1"
then
    echo >&2 Must supply a \"large objects\" file as parameter
    exit 1
fi

tmp_file=$(mktemp)

if ! test -f "$tmp_file"
then
    echo >&2 Failed to create temporary file
    exit 1
fi

cut -d' ' -f1 "$1" | "$(dirname "$0")"/find-blob.pl --all >"$tmp_file" &&
"$(dirname "$0")"/show-interesting.pl "$tmp_file" <"$1"

rm "$tmp_file"

#   Copyright (C) 2015,2016 Bloomberg Finance L.P.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
