#!/usr/bin/env bash

# SC2016: Expressions don't expand in single quotes, use double quotes for that.
# shellcheck disable=SC2016
index_filter='git ls-files -s |
$RFWORK_DIR/remove-blobs.pl |
git update-index --index-info'

msg_filter='tr \\240 \\040'

# SC2016: Expressions don't expand in single quotes, use double quotes for that.
# shellcheck disable=SC2016
commit_filter='tmp=$(git_commit_non_empty_tree "$@");
[[ $GIT_COMMIT = $tmp ]] || echo >&7 $GIT_COMMIT $tmp;
echo $tmp'

: "${RFWORK_DIR:=$PWD}"
export RFWORK_DIR
git filter-branch\
 --index-filter "$index_filter"\
 --msg-filter "$msg_filter"\
 --commit-filter "$commit_filter"\
 --tag-name-filter cat\
 -- --all\
 7>"$RFWORK_DIR/filter-map.txt" &&
"$(dirname "$0")"/update-commit-map-branch.sh <"$RFWORK_DIR/filter-map.txt"

#   Copyright (C) 2015,2016 Bloomberg Finance L.P.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
